# fly.toml app configuration file generated for letsscience on 2023-08-22T00:37:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "letsscience"
primary_region = "cdg"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[mounts]
source = "litefs"
destination = "/var/lib/litefs"

[env]
JWT_SECRET = "btCs2fBGUKAOHlOF3WyIabKVlFHP5KEk"
SQLITE_PATH = "/litefs/main.db"
